# Generated by Django 5.2.4 on 2025-07-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('sequence_number', models.IntegerField(help_text='Order in which videos appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passing_percentage', models.IntegerField(default=70)),
                ('time_limit', models.IntegerField(help_text='Quiz time limit in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['sequence_number'],
            },
        ),
    ]
