databases:
  - name: videoquizapp
    databaseName: videoquizapp
    user: videoquizapp

services:
  - type: web
    name: videoquizapp
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn video_quiz_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: videoquizapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
